/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   todo.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: adaly <marvin@42.fr>                       +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2017/12/02 12:45:18 by adaly             #+#    #+#             */
/*   Updated: 2017/12/02 13:01:57 by adaly            ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../inc/wolf3d.h"

/*
**FT_RAYCAST
**
**MAKE A RAYCASTING FUNCTION THAT TAKES IN THE COORDINATES OF AN ORIGIN POINT,
**AND THE DIRECTION TO SHOOT THE RAY IN, AND RETURN AN ARRAY OF ALL THE OBJS
**INTERSECTED UNTIL THE RAY EITHER HITS A WALL OR SOMETHING TOTALLY OPAQUE.
**THE ARRAY SHOULD ALSO CONTAIN THE RELEVANT INFORMATION ABOUT WHERE EACH OBJ
**WAS HIT, FOR TEXTURING PURPOSES. THIS CAN BE DONE BY USING THE T_RAY STRUCT.
**
**
**FT_RAYDRAW
**
**THIS FUNCTION SHOULD BE MODIFIED TO TAKE IN THE ARRAY OF INTERSECTIONS,
**WHICH SHOULD BE INCLUDED IN THE T_RAY STRUCT, AND REPEAT THE DRAWING
**PROCESS FOR EACH INTERSECTION. FOR PERSPECTIVE ACCURACY, THE RESULTS OF
**THE RAYCASTING PROCEDURE, WHICH FIND THE DISTANCE AND LINEHIGHT FOR EACH
**RAY, WILL NEED TO BE DONE FOR EACH INTERSECTION, AND EVERY VALUE WILL NEED
**TO BE STORED INDIVIDUALLY SO THAT EACH OBJECT'S SIZE ON SCREEN IS STILL
**CONSISTENT WITH THE DISTANCE FROM THE PLAYER, EVEN IF MULTIPLE TRANSLUCENT
**OBJECTS ARE ALIGNED.
*/
/*
AFTER THE DDA IS COMPLETED AND WE KNOW HOW TO DRAW THE WALL FOR A GIVEN X VALUE
ON THE SCREEN, THEN WE CAN GO BACKWARDS OVER THE RAY, DECREMENTING/INCREMENTING
NOT VIA DDA, BUT BY SOME DISTANCE SET IN A MACRO, EACH TIME CHECKING TO SEE IF
THIS SPOT INTERSECTS ANY 3D OBJECT IN THE ENVIRONMENT. IT USES THIS TO ASSEMBLE
A LIST OF INTERSECTIONS ALSO STORED AS ELEMENTS IN A T_RAY ARRAY. AFTER ALL THE
STEPS ARE CHECKED ALONG THE RAY, ANY INTERSECTIONS ARE THEN PROCESSED IN A SIMI
LAR FASHION AS THE INITIAL WALL RAYCASTING, BUT LAID OVER THE WALL TEXTURE.

HAVE TO CREATE A FUNCTION THAT CAN AVERAGE TWO T_PIX VALUES AND COME UP WITH A
COLOR THAT REFLECTS THE RESULT OF OVERLAYING ONE OVER THE OTHER, BY TAKING ADV
ANTAGE OF THE ALPHA CHANNEL.
*/
